# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9b3b094709ed45d41556251368a4f449aa46353d6cd56faf979dbb350a87883b3147f20546e51077479d2bb9ddaead3f3bd3cba4e69f0c8f0e3214930c00c17

test:
  secret_key_base: 4181e9fe680d1e4aa792b411e667a87854803fe624cc2938900edc0894b25005196cd445f12cce4c9525b9d7a496a002a911ba07af38f5d619530e2bd80bb271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
